# Generated by Django 4.1.7 on 2023-03-07 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0002_cropmodel_thumb_croprotationmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="croprotationmodel",
            name="period",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
