# Generated by Django 4.1.7 on 2023-03-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0003_croprotationmodel_period"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="croprotationmodel",
            name="period",
        ),
        migrations.AddField(
            model_name="croprotationmodel",
            name="end",
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name="croprotationmodel",
            name="start",
            field=models.DateTimeField(default=None),
        ),
    ]
