# Generated by Django 4.1.7 on 2023-03-13 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmer', '0004_remove_croprotationmodel_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='croprotationmodel',
            name='farmer',
        ),
        migrations.AddField(
            model_name='croprotationmodel',
            name='farmer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
