# Generated by Django 4.1.7 on 2023-03-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_remove_croprotationmodel_farmer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='croprotationmodel',
            name='crop',
        ),
        migrations.AddField(
            model_name='croprotationmodel',
            name='crop',
            field=models.ManyToManyField(to='farmer.cropmodel'),
        ),
    ]
